### ISSUE TITLE
Flakes support

### ISSUE THREAD

**Issue by roosemberth** [korayal/hls-nix#6]
Hello,

Could you please consider adding support for using [Nix flakes](https://nixos.wiki/wiki/Flakes)?

Nix flakes are an experimental feature on Nix 2.0 soon to be released and in broad usage already across the Nix community. I'll be happy to provide some assistance if the migration path is unclear.

**Comment by korayal** [comment]
Hi,

I haven't been keeping this repository up-to-date after seeing a way to use HLS binaries directly. 

But if you would like to add that kind of support for nix flakes, I'm totally OK with it. And if this repository is still of use for people, I can continue to keep it up-to-date.

**Comment by roosemberth** [comment]
Thanks for your reply.

Actually I found [this](https://github.com/NixOS/nixpkgs/pull/99519) in the meantime which solves my needs. It has not been backported to 20.09, but I decided to move to nixpkgs/unstable instead.

Maybe add a note to the repository README, since people that stumble across this repo probably want to use that instead?

Cheers.

**Comment by korayal** [comment]
Thanks, I was waiting for [easy-hls-nix](https://github.com/jkachmar/easy-hls-nix) to be up, thanks to @jkachmar it's now accessible in github, and also has Flakes support. I'll be updating the README to point to that repository.
